-- 코드를 작성해주세요
-- 비트연산 &을 했을때 해당하는 스킬만 남는 조건으로 OR 연산 하기
SELECT ID, EMAIL,FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT CODE FROM SKILLCODES where NAME='C#'))>0
OR (SKILL_CODE & (SELECT CODE FROM SKILLCODES where NAME='Python'))>0
ORDER BY ID ASC;