-- 코드를 입력하세요
SELECT UB.TITLE, UB.BOARD_ID,UG.REPLY_ID, UG.WRITER_ID, UG.CONTENTS, UG.CREATED_DATE
FROM USED_GOODS_BOARD AS UB
INNER JOIN USED_GOODS_REPLY AS UG
ON UB.BOARD_ID = UG.BOARD_ID 
WHERE YEAR(UB.CREATED_DATE) = '2022' AND MONTH(UB.CREATED_DATE) = '10'
ORDER BY UG.CREATED_DATE ASC, UB.TITLE ASC;